### ISSUE TITLE
Incorrect relation types measurement

### ISSUE THREAD

**Issue by STayinloves** [uma-pi1/kge#103]
The function to classify relations into 1-N, M-1, 1-1, M-N seems incorrect. I get the statistic of FB15k dataset and there's a discrepancy with the statistic reported in (Bordes et al 2013).

Current statistic
```
1-N 0.026765799256505577
M-N 0.9159851301115242
M-1 0.055762081784386616
1-1 0.001486988847583643
```

While it's described as "We obtained that FB15k has 26.2% of 1-TO-1 relationships, 22.7% of 1-TO-MANY, 28.3% of MANY-TO-1, and 22.8% of MANY- TO -MANY" in (Bordes et al 2013).

I modified the code a little bit based on my own understanding and get the following statistic which is more reasonable.
```
1-N 0.21933085501858737
M-N 0.2
M-1 0.2788104089219331
1-1 0.30185873605947955
```

Code changes
https://github.com/uma-pi1/kge/blob/master/kge/indexing.py#L102
```
relation_stats[prefix[p], 0 + p * 2] = relation_stats[prefix[p], 0 + p * 2] + len(labels)
```

I can help PR if this change is correct.

**Comment by samuelbroscheit** [comment]
Yes, your change is correct, it should have been an increment not an assignment. Please do a PR. Thanks for your input!
