### ISSUE TITLE
Support setting verboseness of jobs

### ISSUE THREAD

**Issue by samuelbroscheit** [uma-pi1/kge#105]
Adding verbose to job is a good idea, but that requires even more changes (e.g., to apply it consistently) and is better suited to another PR. 

For now, I suggest to use a default-true `verbose` argument only for evaltraininglossjob.

_Originally posted by @rgemulla in https://github.com/_render_node/MDIzOlB1bGxSZXF1ZXN0UmV2aWV3VGhyZWFkMjY3MzIyODc5OnYy/pull_request_review_threads/discussion_

**Comment by samuelbroscheit** [comment]
This commit does not support setting verboseness of jobs.

**Comment by rgemulla** [comment]
It does. Simply set verbose=False in the config that the job uses.

**Comment by samuelbroscheit** [comment]
Internally ok, but I meant train.verbose and eval.verbose.
