### ISSUE TITLE
Separate evaluation per query type (head, relation, tail)

### ISSUE THREAD

**Issue by STayinloves** [uma-pi1/kge#107]
One-to-many and many-to-one relations are concepts with regard to which entity (head or tail) we're predicting, I'm not sure whether the current evaluation code mixed these two cases.

**Comment by rgemulla** [comment]
Can you clarify? Bordes et al. (2013) states "For example, a relationship having an average of 1.2 head per tail and of 3.2 tails per head was classified as 1-to-Many". 

@samuelbroscheit Do our numbers / our method match the one of Bordes et al.?

**Comment by STayinloves** [comment]
Sorry for the vague description, I mean for 1-to-many relation, it's hard to predict the tail entity but it's easy to predict the head entity, thus the results are presented separately in Bordes et al. (2013). 
<img width="731" alt="image" src="https://user-images.githubusercontent.com/18565449/82909645-8c0e8180-9f37-11ea-8c3d-bf71b52db87d.png">

**Comment by rgemulla** [comment]
Ahh, I see. This is a useful feature to have in general (even independently of the relationship type). I'll rename this issue accordingly.

**Comment by rgemulla** [comment]
Added via 1d26e63b65380e2c13db2ecb3986e69f404efdc2.
