### ISSUE TITLE
Change structure of sp-o and po-s indexes

### ISSUE THREAD

**Issue by AdrianKs** [uma-pi1/kge#109]
The current file structure for sp-o and po-s indexes leads to pickle files, which are very large. For example for wikidata5m index-train_sp_to_o.pck more than 5GB.

If we would store the index via torch.save instead of pickle.dump this size is already reduced to 2.3GB, but loading the file and constructing the indexes still takes way to long.

We could sort the data once for sp and once for po and keep these sorted sets around. Then we just have to store the beginning and end index for each sp/po pair.

**Comment by rgemulla** [comment]
We probably have to switch to torch.save anyway with PyTorch 1.5. As for the layout: yes, one could use sorted arrays + indexes, but this would mean larger changes to the code and a somewhat more cumbersome use of the indexes.

**Comment by samuelbroscheit** [comment]
https://github.com/uma-pi1/kge/issues/9 is also very much related to this. Having long indexes is not necessary for our applications in the foreseeable future. Therefore we only need to convert them to long when they are use for indexing, i.e. at the very last moment.

**Comment by rgemulla** [comment]
Yes, although #9 is about memory, this one about loading speed. The plan is to add a wrapper to the indexes that manage access so that we can store the index more efficiently internally.  I like the idea of addressing #9 simultaneously.

**Comment by samuelbroscheit** [comment]
https://github.com/uma-pi1/kge/issues/9 also affects loading speed and general memory bandwidth bottlenecks because the storage is greatly reduced.

**Comment by rgemulla** [comment]
Addressed with PR #113
