### ISSUE TITLE
FileNotFoundError when running concurrent tasks

### ISSUE THREAD

**Issue by STayinloves** [uma-pi1/kge#111]
When running multiple concurrent tasks in one working directory, the following exception is thrown from time to time, possibly due to multiple processes competing for one file.

```
File "/kge/kge/kge/dataset.py", line 412, in _pickle_dump_atomic
  os.replace(tmpfile, pickle_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'data/wnrr/index-train_sp_to_o.pckl.tmp' -> 'data/wnrr/index-train_sp_to_o.pckl'
```

Naming the file to a different name could be a naive solution, but it could fail when the seed is fixed.

**Comment by AdrianKs** [comment]
I added a UUID to the temporary pickle file name. This should fix the FileNotFoundError.

**Comment by rgemulla** [comment]
Should work. An alternative approach is to use `tempfile`, which also takes care of clean-up in case of errors.

**Comment by rgemulla** [comment]
Please reopen if the issue still occurs.
