### ISSUE TITLE
Installation requires Python version >= 3.7

### ISSUE THREAD

**Issue by alexrenz** [uma-pi1/kge#128]
I just tried to install libKGE and got the following error message:

```
ERROR: Could not find a version that satisfies the requirement ax-platform==0.1.10 (from libkge==0.1) (from versions: 0.0.0, 0.1.0, 0.1.1, 0.1.2, 0.1.3, 0.1.5, 0.1.6, 0.1.7, 0.1.8, 0.1.9)
ERROR: No matching distribution found for ax-platform==0.1.10 (from libkge==0.1)
```

I looked into this and it turned out that the `ax-platform==0.1.10` dependency requires Python version >= 3.7 (see this page: https://pypi.org/project/ax-platform/0.1.10/). Because my machine was using Python 3.6 by default, I got the error message. Switching to Python 3.7 solved the problem. 

I did not see this mentioned anywhere (did I miss it?). If it is not stated yet, you might want to consider mentioning this.

**Comment by AdrianKs** [comment]
Thanks for reporting this. I added the python version specification to the setup.py in this commit: 3631277
