### ISSUE TITLE
Converting mentions to indices using KgeModel

### ISSUE THREAD

**Issue by apoorvumang** [uma-pi1/kge#130]
We can get indices -> mention (string) 
```
model = KgeModel.create_from(checkpoint)
e = torch.Tensor([0, 2,]).long()   
print(model.dataset.entity_strings(e)) 
```
Is it possible to do the reverse using this class ie string -> index? 

I need to do this since I want to get the entity embedding for a given string, so I can do something like
```
embedder = model.get_s_embedder()
e = 'entity_string'
e_id = model.dataset.entity_id(e)  // some function that does this
input = torch.LongTensor([e_id])
entity_embedding = embedder._embeddings(input)
```
I see that there is a function ``entity_ids`` in ``dataset.py`` but I couldn't figure out if it can be used to accomplish this

**Comment by apoorvumang** [comment]
I see that it's possible to map strings -> id using ``entity_ids.del`` file in data, but is it also possible through KgeModel class?

**Comment by rgemulla** [comment]
Not right now. The handling of entity strings will most likely be revised (e.g., so support multiple mentions and to handle new mentions). 

The currently easiest way is to create such an index yourself: e.g., `string_to_index_map = { k: i for i, k in enumerate(dataset.entity_strings()) }`.

**Comment by rgemulla** [comment]
I forgot: note that there is no guarantee that the entity_strings are unique (they need to be to do backward mapping).
