### ISSUE TITLE
Variance between runs with same config.yaml

### ISSUE THREAD

**Issue by apoorvumang** [uma-pi1/kge#134]
I noticed there is a slight variance in MRR, mean rank and other evaluation criteria when I train models using kge with the same config.yaml

For example, I ran ComplEx twice using the best config provided for FB15k-237 and obtained the following results 

Run 1:
```
[3530b3f8]   mean_rank_filtered_with_test: 155.52497861420017
[3530b3f8]   mean_reciprocal_rank_filtered_with_test: 0.35341549044767606
```
Run 2:
```
[375210d0]   mean_rank_filtered_with_test: 157.8696891930425
[375210d0]   mean_reciprocal_rank_filtered_with_test: 0.35235344044054745
```
Of course these are very minor differences, but seeing how recent trends consider 0.353 as an improvement over 0.352, I am wondering just in case you have done any analysis on the variance of results. I see that the results in the Appendix show mean MRR but not the variance (for a fixed config). This might be useful if we want to say whether the improvement of one model over another is statistically significant or not.

**Comment by rufex2001** [comment]
You can see mean + std of a single model reported in Table 9 of our paper:

https://openreview.net/forum?id=BkxSmlBFvr

I personally don't think 35.2 to 35.3 (or small changes like that without
reference) should be considered an improvement, and it would be nice if
reporting variance of best models became the norm.

**Comment by apoorvumang** [comment]
Thanks, sorry I missed that table
