### ISSUE TITLE
contradiction in requirements

### ISSUE THREAD

**Issue by zxgx** [uma-pi1/kge#153]
Package 'dataclasses' requires Python in '>=3.6, <3.7', while package 'libkge' requires Python in '>=3.7'.   
How can I install libkge??  
![1](https://user-images.githubusercontent.com/34452939/96406553-3c945f00-1212-11eb-94f8-d64ea6bde95d.png)

**Comment by AdrianKs** [comment]
Thanks for reporting this. The dataclasses dependency is not needed anymore from python 3.7 on.
I removed the dependency from the setup file in this commit: https://github.com/uma-pi1/kge/commit/17b6af55b8506ec8bec5b3b4593845149481353a
