### ISSUE TITLE
Pretrained embeddings for Freebase 2M dataset

### ISSUE THREAD

**Issue by datha88** [uma-pi1/kge#156]
Hello,
Will you be providing Pretrained embeddings for Freebase 2M dataset?

Thanks!

**Comment by rgemulla** [comment]
Currently not planned.

@AdrianKs Do you have a link to the search job we used for wikidata5m so that @datha88 can train the embeddings without to much hassle?

**Comment by AdrianKs** [comment]
You can use the [wikidata search configuration](http://web.informatik.uni-mannheim.de/pi1/libkge-models/wikidata5m-complex-search.yaml).
It will train 30 trials for up to 20 epochs. You can then train the best two models for up to 400 epochs. This should probably give you some good results on Freebase 2m.
