### ISSUE TITLE
Support for entity/relation independent parameters for RelationalScorer?

### ISSUE THREAD

**Issue by apoorvumang** [uma-pi1/kge#170]
Hi

This is just a feature suggestion. Some recent models eg. https://arxiv.org/abs/2008.12813 use parameters other than entity/relation embeddings to calculate spo score. These parameters are usually part of the model, but not specific to an entity or relation - for eg. you may want to pass the embeddings through a transformer (same transformer regardless of entity/relation).

Currently (from my understanding) RelationalScorer only uses entity/relation embeddings. Is there an easy way to pass extra entity/relation-agnostic parameters - or a reference to the KgeModel object itself - to the scorer using the current implementation? 

Thanks

**Comment by apoorvumang** [comment]
I am working on a model that requires such parameters, and wanted to use libKGE if possible, hence the suggestion

**Comment by rgemulla** [comment]
Sure, just declare these parameters as part of the scorer. Have a look at implementation of the [ConvE scorer](https://github.com/uma-pi1/kge/blob/master/kge/model/conve.py) for an example.

Is this what you meant?

**Comment by apoorvumang** [comment]
Thanks, exactly what I wanted!
