### ISSUE TITLE
Using Custom Datasets?

### ISSUE THREAD

**Issue by sbonner0** [uma-pi1/kge#174]
Hi - thanks for the code, it looks like a great package. 

Stupid question from my side - is there a simple way for me to use my own dataset with this package? I read the readme and I couldn't see that option mentioned anywhere....my apologies if I have missed something obvious!

**Comment by rgemulla** [comment]
Yes, we should document this better. 

For now: create a subfolder (= dataset name) in the `data` folder, then store in it a file called `dataset.yaml` as well as the data itself. You can then use the dataset by specifying the folder name as `dataset.name` in your job's configuration file.

Have a look at the provided `toy` example (under `data/toy`). The configuration keys and file format is documented (https://github.com/uma-pi1/kge/blob/2b693e31c4c06c71336f1c553727419fe01d4aa6/kge/config-default.yaml#L48)[here].

**Comment by sbonner0** [comment]
Ah great, thanks for your response. I'll give it a go now.

**Comment by rgemulla** [comment]
I forgot: the data can be automatically preprocessed and converted into the format required by LibKGE. Here is the relevant part for the toy dataset:

```sh
# run in data folder

# download
curl -O http://web.informatik.uni-mannheim.de/pi1/kge-datasets/toy.tar.gz
tar xvf toy.tar.gz

# preprocess
python preprocess/preprocess_default.py toy
```

**Comment by vefthym** [comment]
@rgemulla your instructions were very helpful to answer the same question on my side, so I think they should be part of the readme (esp. your follow-up answer). Great tool and worked very smoothly on my dataset, thanks!

**Comment by rgemulla** [comment]
Thanks, I added these instructions to the main page.
