### ISSUE TITLE
Error when running negative_sampling with implementation: auto

### ISSUE THREAD

**Issue by nluedema** [uma-pi1/kge#178]
When I am running negative_sampling with implementation set to auto I get the following error:
`ValueError: Illegal value auto for key negative_sampling.implementation; allowed values are ['triple', 'batch', 'all']`

The error occurs in the init of `BatchNegativeSample`
```Python
self._implementation = self.check_option(
    "implementation", ["triple", "batch", "all"]
)
```

I had a look into the code and I think the problem is in the init of `TrainingJobNegativeSampling`
```Python
self._sampler = KgeSampler.create(config, "negative_sampling", dataset)
self._implementation = self.config.check(
    "negative_sampling.implementation", ["triple", "all", "batch", "auto"],
)
if self._implementation == "auto":
    max_nr_of_negs = max(self._sampler.num_samples)
    if self._sampler.shared:
        self._implementation = "batch"
    elif max_nr_of_negs <= 30:
        self._implementation = "triple"
    elif max_nr_of_negs > 30:
        self._implementation = "batch
```

It is checked which is the best implementation, but this decision never reaches `BatchNegativeSample`. I would propose the following fix for the init of `TrainingJobNegativeSampling`
```Python
self._sampler = KgeSampler.create(config, "negative_sampling", dataset)
self._implementation = self.config.check(
    "negative_sampling.implementation", ["triple", "all", "batch", "auto"],
)
if self._implementation == "auto":
    max_nr_of_negs = max(self._sampler.num_samples)
    if self._sampler.shared:
        self._implementation = "batch"
    elif max_nr_of_negs <= 30:
        self._implementation = "triple"
    elif max_nr_of_negs > 30:
        self._implementation = "batch
    self.config.set("negative_sampling.implementation", self._implementation)
```

**Comment by rgemulla** [comment]
I agree & thanks. Can you do a PR? I also suggest to (i) make the last `elif` an `else` and (ii) in the set, add the option `log=True` so that the specific choice is reported correctly.

**Comment by AdrianKs** [comment]
should we additionally also change the default implementation to auto? Otherwise most users will use the slow triple implementation.

**Comment by rgemulla** [comment]
I don't see why not.

**Comment by nluedema** [comment]
@rgemulla I can do the PR. Regarding `log=True`, in the init of `TrainingJobNegativeSampling` the negative sampling implementation is already written to the log
```
config.log(
    "Initializing negative sampling training job with "
    "'{}' scoring function ...".format(self._implementation)
)
```
Should I still add `log=True` for the set operation?

**Comment by rgemulla** [comment]
Yes, we always do this when changing user-specified config parameters.

**Comment by nluedema** [comment]
I created the PR #179
