### ISSUE TITLE
Installation doesn't work with python 3.9 but works with 3.7

### ISSUE THREAD

**Issue by apoorvumang** [uma-pi1/kge#181]
Hi

I was trying a fresh install using the instructions stated in the readme. My python version was 3.9. I got several error messages related to installation of numba and llvmlite, possibly due to https://github.com/numba/numba/issues/6345. Installation works fine with python 3.7

Maybe updating the requirements in setup.py regarding python version could help other people trying to install libkge? Currently its python_requires='>=3.7' I think.

Thanks

**Comment by rgemulla** [comment]
Good point, thanks!
