### ISSUE TITLE
Support failing trials but continueing search

### ISSUE THREAD

**Issue by fratajcz** [uma-pi1/kge#182]
Hi!

I have noticed that when my grid search reaches extreme points (like max dimension, max batch size and max number of negative samples) the trial crashes and takes down the whole search with it. Now there is nothing one can do about the trial crashing i.e. due to a OOM Error, but the search could very well continue. Right now I test my search's extreme points in a preliminary training job with all the parameters maxed out to see if it runs. If it doesnt, I keep decreasing the factor that is least influential on the model performance (which in this case probably is the batch size) until it doesn't crash anymore. However, this clearly limits the grid i can search on. For example, in a recent case I had to bring my batch size down to 40 while it was running just fine with much higher values for most of the points in the grid. 

It would be great if we could get that kind of failed-trial-handling in an upcoming version. I apologize if it is already implemented and just requires certain config settings. 

Cheers and Thanks!

**Comment by rgemulla** [comment]
Try setting config key `search.on_error` to `continue`. Does this work for you?

**Comment by rgemulla** [comment]
BTW: larger batch sizes are also supported, set `train.subbatch_auto_tune` to `true` to simulate larger batch sizes on GPUs with less memory.

**Comment by fratajcz** [comment]
Ugh I am sorry, I must be blind. I will try this immediately and let you know. Is there a reason why ```search.on_error``` isn't set to ```continue``` by default?

**Comment by rgemulla** [comment]
To make you aware that there was an error ;)

**Comment by fratajcz** [comment]
Well it definitely accomplished that :D

**Comment by rgemulla** [comment]
@fratajcz Is this issue resolved?
