### ISSUE TITLE
Grid Search not working due to wrong string for config lookup

### ISSUE THREAD

**Issue by sailera19** [uma-pi1/kge#185]
Grid Search is not working because it uses for the configuration of the manual search for key "search.type" the value "manual" instead of "manual_search" that was used in grid_search.py.

Configuration:
![image](https://user-images.githubusercontent.com/8994785/109217135-bab2d480-77b5-11eb-80b9-c5d5f435e7c0.png)

Error:
![image](https://user-images.githubusercontent.com/8994785/109216711-2e081680-77b5-11eb-8703-114b7521c501.png)

**Comment by AdrianKs** [comment]
Thank you for reporting and fixing this.
