### ISSUE TITLE
Grid and Manual Search memory leakage

### ISSUE THREAD

**Issue by sailera19** [uma-pi1/kge#187]
The manual search has a memory leakage that is also affecting the grid search. It is caused by the job object and the underlying embeddings that are not being released after the job is done.
After every job search there is an increase in the memory allocated and reserved.

Without Fix:

- Beginning of first training job:

![image](https://user-images.githubusercontent.com/8994785/109219256-a8d23100-77b7-11eb-9fc2-9dafe90a4cc0.png)

- Beginning of second training job:

![image](https://user-images.githubusercontent.com/8994785/109219334-c3a4a580-77b7-11eb-9c40-f93781612cdc.png)

- Beginning of third training job:

![image](https://user-images.githubusercontent.com/8994785/109219392-d8813900-77b7-11eb-97b2-60aec9a60c52.png)

This can be fixed by deleting the job object at the end of the search and calling the garbage collector.

With fix:
- Beginning of first training job:
![image](https://user-images.githubusercontent.com/8994785/109219662-2dbd4a80-77b8-11eb-97e4-6e35eaba889d.png)

- Beginning of second training job:
![image](https://user-images.githubusercontent.com/8994785/109219733-475e9200-77b8-11eb-9667-80615f1f3aa4.png)

- Beginning of third training job:
![image](https://user-images.githubusercontent.com/8994785/109219768-55acae00-77b8-11eb-88a6-027cadd3c28d.png)

The difference between the first and the second training job can be explained by the memory that is used for evaluation at the end of the training job.

Configuration:
![image](https://user-images.githubusercontent.com/8994785/109218453-fd28e100-77b6-11eb-9da4-04fe2694e0c4.png)
with toy-complex-search-grid-memoryleakage.yaml in:
[toy-complex-search-grid-memoryleakage.zip](https://github.com/uma-pi1/kge/files/6045782/toy-complex-search-grid-memoryleakage.zip)

**Comment by sailera19** [comment]
requires #185 to be fixed first

**Comment by AdrianKs** [comment]
Thank you for reporting and fixing this.
