### ISSUE TITLE
How to obtain num_samples parameter for new dataset?

### ISSUE THREAD

**Issue by nitishajain** [uma-pi1/kge#189]
Hello, 

I am leveraging the LibKGE code to train embeddings for a custom dataset and I have a simple query. I am using the grid search code snippet to find the appropriate configuration settings as documented. 
Particularly for the _negative sampling_ technique, the parameter _num_samples_ (number of times each slot of each positive triple is corrupted by the sampler to obtain negative triples) has been pre-specified for the available datasets, e.g. for yago, s is 8919 and o is 8942. I want to understand how these parameters were decided and how can I obtain the same for a new dataset. 

While the default values in the code are 3, this results in quite bad results, how could I obtain the appropriate s and o values for a new dataset? Would appreciate any pointers, maybe I have missed something obvious.

Thank you.

**Comment by rgemulla** [comment]
They were found by a hyperparameter search: first random search, then Bayesian optimization. You can do the same for your dataset/model combination, see [here ](https://github.com/uma-pi1/kge-iclr20) for details on how to do this.

**Comment by rgemulla** [comment]
@AdrianKs Perhaps we should put the actual search configs for YAGO and Wikidata on the main page as well.

**Comment by nitishajain** [comment]
Thank you very much, the documentation at the link is quite helpful. I'm trying out the same.
