### ISSUE TITLE
Question on negative sampling

### ISSUE THREAD

**Issue by unai-zulaika** [uma-pi1/kge#193]
Hello,

I apologize for asking what's probably a dumb question.

 I'm trying to understand in which lines of the code are negative samples used for training with the default configuration for rescal_FB15k-237. However, I'm can not find it, since it seems that "TrainingJobNegativeSampling" class is not being used in the process although negative_training is set up in the configuration. 

Could someone please clarify this for me?

Thank you!

**Comment by rgemulla** [comment]
What do you mean by default configuration? When `train.type` is set to `negative_sampling` , then indeed class `TrainingJobNegativeSampling` will be used. See also [here](https://github.com/uma-pi1/kge/blob/d0634774b1b29afc739454737aa105dec6cb60b2/kge/job/train.py#L127) and [here](https://github.com/uma-pi1/kge/blob/d0634774b1b29afc739454737aa105dec6cb60b2/kge/config-default.yaml#L329).

**Comment by unai-zulaika** [comment]
I see, thank you for the answer.

I was referring to the config.yaml of the pretrained RESCAL for [FB15k-237](http://web.informatik.uni-mannheim.de/pi1/iclr2020-models/fb15k-237-rescal.yaml). I was confused because it sets a few "negative_sampling" (I suppose they can be ignored) values but I now realize it uses 1vsAll train.type! 

Thank you!

**Comment by rgemulla** [comment]
Yes, they can be ignored because the train.type is set differently. It's an artifact of the hyperparameter search that these values appear in the config file.
