### ISSUE TITLE
Get the relation embedding

### ISSUE THREAD

**Issue by novice7** [uma-pi1/kge#194]
Hi,I have trained the ComplEx  model in my dataset,  is there some way to get the relation embedding when I have the subject embedding and object embedding ?

**Comment by rufex2001** [comment]
Hi, could you please provide some more context? Thanks!

**Comment by novice7** [comment]
I get the embedding of entity A and B , and I want to get the relation  embedding between them

**Comment by novice7** [comment]
If I haven't made you understand, please let me know. Thanks!

**Comment by rufex2001** [comment]
It is still unclera to me what exactly it is that you want to do. Given the embeddings of two entities A and B, you want to find the relations between those two entities. Is that it? Or are you after the relation paths that connect A and B?

**Comment by novice7** [comment]
I want to find the relations between those two entities.

**Comment by rgemulla** [comment]
The relation embedding does not depend on the entities involved. If you want to score every possible relation between a pair of entities, however, use https://github.com/uma-pi1/kge/blob/d0634774b1b29afc739454737aa105dec6cb60b2/kge/model/kge_model.py#L727

**Comment by novice7** [comment]
Okay, thanks a lot!!
