### ISSUE TITLE
Running on cpu throws error 

### ISSUE THREAD

**Issue by sanjanasri** [uma-pi1/kge#208]
Hi all,
   
   I tried this command "kge start examples/toy-complex-train.yaml --job.device cpu" and I got the error as in screenshot. please help

![Screenshot from 2021-06-04 09-49-25](https://user-images.githubusercontent.com/13214774/120745182-34c3c980-c51a-11eb-8962-f86dc32b6d72.png)

**Comment by rgemulla** [comment]
Seems to be an issue with numba on your system. Which numba version do you use? With 0.53.1 (as per setup.py) everything works fine on our systems.

**Comment by sanjanasri** [comment]
@rgemulla Thank you for your response.  I reinstalled numba still I get the same error 
![Screenshot from 2021-06-04 23-44-44](https://user-images.githubusercontent.com/13214774/120845835-f74d5380-c58e-11eb-8b56-c6938e8b7c46.png)

**Comment by rgemulla** [comment]
This is not a LibKGE issue; perhaps [this](https://www.mail-archive.com/debian-bugs-rc@lists.debian.org/msg550510.html) helps.
