### ISSUE TITLE
Ax search broken with numpy==1.20.x

### ISSUE THREAD

**Issue by AdrianKs** [uma-pi1/kge#209]
Search with Ax can not create a trial but only returns "type object has no attribute dtype".

Reproducible with `kge start examples/toy-complex-search-ax.yaml`

Workaround: downgrade to numpy==1.19.*

Probably related bug report on pandas: https://github.com/pandas-dev/pandas/issues/39520
Also related to issue #198

**Comment by rgemulla** [comment]
What about upgrading ax instead?

**Comment by AdrianKs** [comment]
newest ax release is 1.20.0 released in February. This does not yet fix this bug.
See releases here: https://github.com/facebook/Ax/releases

**Comment by AdrianKs** [comment]
unfortunately, with a downgrade of numpy we would also need to downgrade numba again

**Comment by rgemulla** [comment]
Yes, let's do this then. It's better than a broken package.

**Comment by AdrianKs** [comment]
done in 77f257f
