### ISSUE TITLE
Downloading datasets with curl broken for some datasets

### ISSUE THREAD

**Issue by rufex2001** [uma-pi1/kge#210]
@AdrianKs found today that the downloads_all.sh script does not work for some datasets, as it downloads an HTML file instead of the actual tar.gz file with the data. I confirmed this behavior as well. We are both on some version of Ubuntu.

I found the issue to be with _curl_, as the files on the server are fine. I am not sure why the script worked before and it doesn't now, but an easy fix is to add the -L flag to the download command, i.e.

curl -O -L http://web.informatik.uni-mannheim.de/pi1/kge-datasets/wn11.tar.gz

Before fixing this, I'd like to confirm this is an issue for other systems as well, e.g. Windows.

**Comment by rgemulla** [comment]
Probably the server conf has been changed to require https. Instead of -L, I suggest to simply use https.

**Comment by rufex2001** [comment]
Indeed that did it! Solved in 8a68a13cdfb4004dcad2c23b71d00711258ad8d5
