### ISSUE TITLE
Error in Installation

### ISSUE THREAD

**Issue by ShoRit** [uma-pi1/kge#212]
I get the following error during installation, when I do 
**pip install -e .**

ERROR: Could not find a version that satisfies the requirement numpy==1.19.*torch==1.7.1 (from libkge)
ERROR: No matching distribution found for numpy==1.19.*torch==1.7.1

However, for my conda environment, I satisfy both the criteria. Could you suggest a fix? 

<img width="617" alt="image" src="https://user-images.githubusercontent.com/15673954/121641154-ada7b180-ca43-11eb-806f-8291e2684ae8.png">

Thanks

**Comment by ashispapu** [comment]
Please correct the `setup.py` file as below

 `install_requires=[        "numpy==1.19.*"        "torch==1.7.1", `
Here `,` is missing after  "numpy==1.19.*" . Add a `,` and it should be installed.
 `install_requires=[        "numpy==1.19.*" ,       "torch==1.7.1", `

**Comment by AdrianKs** [comment]
thanks, just saw that and fixed it.
setup should work again

**Comment by ShoRit** [comment]
Thanks a bunch. I did not even think about this here.
