### ISSUE TITLE
How to get the trained embedding matrix

### ISSUE THREAD

**Issue by SRL94** [uma-pi1/kge#214]
How to get the trained embedding matrix from checkpoint?

**Comment by rufex2001** [comment]
The checkpoint.pt files contain the learned embedding matrices. These are
saved with torch.save, so you can load them with torch.load. You can then
check the contents of the file as with any dictionary. The embedding
matrices are torch tensors, and you can convert them to whatever you need,
e.g. numpy arrays.

**Comment by AdrianKs** [comment]
They are actually still stored with the module pickle. Could be though that torch.load still works.
We also provide a function to load checkpoints:
```python
from kge.util import load_checkpoint
checkpoint = load_checkpoint("path/to/checkpoint")
```

**Comment by AdrianKs** [comment]
you can then get the matrices from the checkpoint with
```python
entity_embeddings = checkpoint["model"][0]["_entity_embedder._embeddings.weight"]
relation_embeddings = checkpoint["model"][0]["_relation_embedder._embeddings.weight"]
```

**Comment by SRL94** [comment]
> you can then get the matrices from the checkpoint with
> 
> ```python
> entity_embeddings = checkpoint["model"][0]["_entity_embedder._embeddings.weight"]
> relation_embeddings = checkpoint["model"][0]["_relation_embedder._embeddings.weight"]
> ```

Thanks, this is what I need.

**Comment by oliver-lloyd** [comment]
Hi, perhaps a silly question but could someone please confirm if the order of entity embedding vectors in the loaded dict is aligned with with the dataset's entity index (entity_ids.del)?

**Comment by rgemulla** [comment]
Yes, that's exactly the indexing/order used internally. (Note that the embeddings are not stored in a dict though; see lookup_embedder.py.)
