### ISSUE TITLE
Running OOM even with toy example

### ISSUE THREAD

**Issue by jrbn** [uma-pi1/kge#215]
Dear LibKGE team,

thank you for this great library! My intention was to use it to train the embedding of some KGs but I did not manage to complete the training of the toy example because of a potential bug in the code. Basically, the speed of training deteriorates very quickly and the library takes all the available memory until it is finished. 

Steps to replicate this problem:

I've downloaded the code both on my laptop (macos) and on a linux machine. I've installed the library with pip and then launched the program "kge start examples/toy-complex-train.yaml --job.device cpu" (the problem occurs also if I use GPUs). My laptop has 32GB of RAM while the linux machine has 64GB. The program starts to train the model but it does not reach the end of the first epoch. The first batches are trained quickly, but already after 10-20 batches the program slows down considerably until all the RAM is taken. I'm using Python 3.8.2/3.8.3 and PyTorch 1.7.1.

Is it normal that it more than 64GB of RAM are needed to train the toy example? It might be that some libraries are not compatible with libkge and this triggers this strange behavior.

Thank you in advance!

**Comment by rgemulla** [comment]
Thanks you for reporting this! I've reverted the last change (9a4f69a806ea775fed13657a3e3cd1c6711a2279), which introduced this bug for now.

**Comment by rgemulla** [comment]
Please reopen if that does not fix your problem.
