### ISSUE TITLE
kge --help error message

### ISSUE THREAD

**Issue by tsamoura** [uma-pi1/kge#216]
Dear libkge team, 

I downloaded and installed libkge using the instructions in the README file. The installation completed without any error messages. However, when I am running the command "kge --help" within the kge folder, I get the following message: 

(base) e.tsamoura@wsc-1835-2:~/Downloads/kge$ kge --help
Traceback (most recent call last):
  File "/home/SERILOCAL/e.tsamoura/anaconda3/bin/kge", line 11, in <module>
    load_entry_point('libkge', 'console_scripts', 'kge')()
  File "/home/SERILOCAL/e.tsamoura/anaconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/SERILOCAL/e.tsamoura/anaconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/home/SERILOCAL/e.tsamoura/anaconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/home/SERILOCAL/e.tsamoura/anaconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/SERILOCAL/e.tsamoura/Downloads/kge/kge/cli.py", line 11, in <module>
    from kge.job import Job
  File "/home/SERILOCAL/e.tsamoura/Downloads/kge/kge/job/__init__.py", line 4, in <module>
    from kge.job.train import TrainingJob
  File "/home/SERILOCAL/e.tsamoura/Downloads/kge/kge/job/train.py", line 16, in <module>
    from kge.model import KgeModel
  File "/home/SERILOCAL/e.tsamoura/Downloads/kge/kge/model/__init__.py", line 17, in <module>
    from kge.model.rotate import RotatE
  File "/home/SERILOCAL/e.tsamoura/Downloads/kge/kge/model/rotate.py", line 198, in <module>
    @torch.jit.script
  File "/home/SERILOCAL/e.tsamoura/anaconda3/lib/python3.7/site-packages/torch/jit/__init__.py", line 691, in script
    _jit_script_compile(mod, ast, _rcb, get_default_args(fn))
RuntimeError: 
arguments for call are not valid:
  
  for operator aten::norm(Tensor self, Scalar p=<default>) -> Tensor:
  keyword argument dim unknown
  
  for operator aten::norm(Tensor self, Scalar p, int dim, bool keepdim=<default>) -> Tensor:
  argument p not provided.
  @torch.jit.script
  def abs_complex(x_re, x_im):
      "Compute magnitude of given complex numbers"
      x_re_im = torch.stack((x_re, x_im), dim=0)  # dim0: real, imaginary
      return torch.norm(x_re_im, dim=0)  # sqrt(real^2+imaginary^2)
             ~~~~~~~~~~ <--- HERE
  
  for operator aten::norm(Tensor self, Scalar p, int dim, bool keepdim=<default>, *, Tensor out) -> Tensor:
  argument p not provided.
  @torch.jit.script
  def abs_complex(x_re, x_im):
      "Compute magnitude of given complex numbers"
      x_re_im = torch.stack((x_re, x_im), dim=0)  # dim0: real, imaginary
      return torch.norm(x_re_im, dim=0)  # sqrt(real^2+imaginary^2)
             ~~~~~~~~~~ <--- HERE
for call at:
@torch.jit.script
def abs_complex(x_re, x_im):
    "Compute magnitude of given complex numbers"
    x_re_im = torch.stack((x_re, x_im), dim=0)  # dim0: real, imaginary
    return torch.norm(x_re_im, dim=0)  # sqrt(real^2+imaginary^2)
           ~~~~~~~~~~ <--- HERE


Can you please advice me what to do? For your record, I have already tried to uninstall and install kge for the second time. 

Regards,
Efi

**Comment by tsamoura** [comment]
Hi all,

I uninstalled and installed pytorch and then repeated the installation process. It seems to work fine now, although it would be good to look at this issue in case other users experience it as well.

**Comment by rgemulla** [comment]
Why pytorch version are you using? This seems to be a bug that has already been fixed: https://github.com/pytorch/pytorch/issues/20113

**Comment by tsamoura** [comment]
Hi, thanks for the quick reply. 

I was using torch 1.9.0, but it seems that during the installation process, it got downgraded to 1.7.1.
Below is the detailed message I got. 

(base) e.tsamoura@wsc-1835-2:~/Downloads/kge$ pip install -e .
Obtaining file:///home/SERILOCAL/e.tsamoura/Downloads/kge
Requirement already satisfied: numpy==1.19.* in /home/SERILOCAL/e.tsamoura/anaconda3/lib/python3.7/site-packages (from libkge==0.1) (1.19.5)
Collecting torch==1.7.1
  Using cached torch-1.7.1-cp37-cp37m-manylinux1_x86_64.whl (776.8 MB)
Requirement already satisfied: pyyaml in /home/SERILOCAL/e.tsamoura/anaconda3/lib/python3.7/site-packages (from libkge==0.1) (5.1.2)
Requirement already satisfied: pandas in /home/SERILOCAL/e.tsamoura/anaconda3/lib/python3.7/site-packages (from libkge==0.1) (1.2.4)
Collecting argparse
  Using cached argparse-1.4.0-py2.py3-none-any.whl (23 kB)
Requirement already satisfied: path in /home/SERILOCAL/e.tsamoura/anaconda3/lib/python3.7/site-packages (from libkge==0.1) (16.0.0)
Requirement already satisfied: ax-platform==0.1.19 in /home/SERILOCAL/e.tsamoura/anaconda3/lib/python3.7/site-packages (from libkge==0.1) (0.1.19)
Requirement already satisfied: sqlalchemy in /home/SERILOCAL/e.tsamoura/anaconda3/lib/python3.7/site-packages (from libkge==0.1) (1.4.19)
Requirement already satisfied: torchviz in /home/SERILOCAL/e.tsamoura/anaconda3/lib/python3.7/site-packages (from libkge==0.1) (0.0.2)
Requirement already satisfied: numba==0.50.* in /home/SERILOCAL/e.tsamoura/anaconda3/lib/python3.7/site-packages (from libkge==0.1) (0.50.1)
Requirement already satisfied: botorch>=0.3.3 in /home/SERILOCAL/e.tsamoura/anaconda3/lib/python3.7/site-packages (from ax-platform==0.1.19->libkge==0.1) (0.4.0)
Requirement already satisfied: plotly in /home/SERILOCAL/e.tsamoura/anaconda3/lib/python3.7/site-packages (from ax-platform==0.1.19->libkge==0.1) (5.1.0)
Requirement already satisfied: scipy in /home/SERILOCAL/e.tsamoura/anaconda3/lib/python3.7/site-packages (from ax-platform==0.1.19->libkge==0.1) (1.6.2)
Requirement already satisfied: scikit-learn in /home/SERILOCAL/e.tsamoura/anaconda3/lib/python3.7/site-packages (from ax-platform==0.1.19->libkge==0.1) (0.24.2)
Requirement already satisfied: jinja2 in /home/SERILOCAL/e.tsamoura/anaconda3/lib/python3.7/site-packages (from ax-platform==0.1.19->libkge==0.1) (3.0.1)
Requirement already satisfied: typeguard in /home/SERILOCAL/e.tsamoura/anaconda3/lib/python3.7/site-packages (from ax-platform==0.1.19->libkge==0.1) (2.12.1)
Requirement already satisfied: setuptools in /home/SERILOCAL/e.tsamoura/anaconda3/lib/python3.7/site-packages (from numba==0.50.*->libkge==0.1) (41.4.0)
Requirement already satisfied: llvmlite<0.34,>=0.33.0.dev0 in /home/SERILOCAL/e.tsamoura/anaconda3/lib/python3.7/site-packages (from numba==0.50.*->libkge==0.1) (0.33.0)
Requirement already satisfied: typing-extensions in /home/SERILOCAL/e.tsamoura/anaconda3/lib/python3.7/site-packages (from torch==1.7.1->libkge==0.1) (3.10.0.0)
Requirement already satisfied: gpytorch>=1.4 in /home/SERILOCAL/e.tsamoura/anaconda3/lib/python3.7/site-packages (from botorch>=0.3.3->ax-platform==0.1.19->libkge==0.1) (1.4.2)
Requirement already satisfied: MarkupSafe>=2.0 in /home/SERILOCAL/e.tsamoura/anaconda3/lib/python3.7/site-packages (from jinja2->ax-platform==0.1.19->libkge==0.1) (2.0.1)
Requirement already satisfied: python-dateutil>=2.7.3 in /home/SERILOCAL/e.tsamoura/anaconda3/lib/python3.7/site-packages (from pandas->libkge==0.1) (2.8.1)
Requirement already satisfied: pytz>=2017.3 in /home/SERILOCAL/e.tsamoura/anaconda3/lib/python3.7/site-packages (from pandas->libkge==0.1) (2021.1)
Requirement already satisfied: six>=1.5 in /home/SERILOCAL/e.tsamoura/anaconda3/lib/python3.7/site-packages (from python-dateutil>=2.7.3->pandas->libkge==0.1) (1.16.0)
Requirement already satisfied: tenacity>=6.2.0 in /home/SERILOCAL/e.tsamoura/anaconda3/lib/python3.7/site-packages (from plotly->ax-platform==0.1.19->libkge==0.1) (8.0.1)
Requirement already satisfied: joblib>=0.11 in /home/SERILOCAL/e.tsamoura/anaconda3/lib/python3.7/site-packages (from scikit-learn->ax-platform==0.1.19->libkge==0.1) (1.0.1)
Requirement already satisfied: threadpoolctl>=2.0.0 in /home/SERILOCAL/e.tsamoura/anaconda3/lib/python3.7/site-packages (from scikit-learn->ax-platform==0.1.19->libkge==0.1) (2.1.0)
Requirement already satisfied: greenlet!=0.4.17 in /home/SERILOCAL/e.tsamoura/anaconda3/lib/python3.7/site-packages (from sqlalchemy->libkge==0.1) (1.1.0)
Requirement already satisfied: importlib-metadata in /home/SERILOCAL/e.tsamoura/anaconda3/lib/python3.7/site-packages (from sqlalchemy->libkge==0.1) (3.10.0)
Requirement already satisfied: zipp>=0.5 in /home/SERILOCAL/e.tsamoura/anaconda3/lib/python3.7/site-packages (from importlib-metadata->sqlalchemy->libkge==0.1) (3.5.0)
Requirement already satisfied: graphviz in /home/SERILOCAL/e.tsamoura/anaconda3/lib/python3.7/site-packages (from torchviz->libkge==0.1) (0.16)
Installing collected packages: torch, argparse, libkge
  Attempting uninstall: torch
    Found existing installation: torch 1.9.0
    Uninstalling torch-1.9.0:
      Successfully uninstalled torch-1.9.0
  Running setup.py develop for libkge
Successfully installed argparse-1.4.0 libkge-0.1 torch-1.7.1

**Comment by rgemulla** [comment]
Thanks! torch 1.9.0 is not yet supported, but we'll keep this in mind once it is.
