### ISSUE TITLE
Missing dataset.yaml files

### ISSUE THREAD

**Issue by Filco306** [uma-pi1/kge#217]
Hello! 

I ran your quickstart instructions, and my I seem to be missing the `dataset.yaml`-file, even for the `toy` example, so it throws an error when I try the last line in the `quickstart` example. Would you guys have any idea why? 

Thanks! 

Cheers

**Comment by rufex2001** [comment]
Did you run the download-all.sh script in the data folder?

**Comment by Filco306** [comment]
Hello! Yes, I immediately found it now, haha. Apparently, `python` does not work for me; instead I had to change to `python3` since `python` is not a command on my server, so I had to change those lines in the script. It is running now, will report back a bit later! 

Either way, it might be good to change that since I guess most people are using python3 and not python, and python3 is always an accurate command, isn't it ?

**Comment by rufex2001** [comment]
That depends on system settings. I get python 3 when using calling *python*.

**Comment by Filco306** [comment]
Yes indeed. I just thought `python3` might hold more generally :) either way, thanks for a great repository, I think it really makes KG embedding comparisons way easier!

**Comment by rufex2001** [comment]
Thanks! That is the main point! Reproducibility!
