### ISSUE TITLE
Yaml-files for the experiments used in the paper

### ISSUE THREAD

**Issue by Filco306** [uma-pi1/kge#219]
Hello, 

First of all, thank you very much for a great package. I think it is extremely good to strive for a unified package to fully enable reproducibility in this field. 

I started using the package recently, and I am still new to using it. I was wondering however; is it possible to obtain the configuration files for the experiments used in the paper? It would be great to be able to re-run these for my own experiments and ensure a fair comparison. 

Thank you! 

Best,
Filip

**Comment by rgemulla** [comment]
Sure! See https://github.com/uma-pi1/kge-iclr20 under "Generating config files". Note that the library has evolved since then, but we've tried to maintain backward compatibility so that the older style config file should still work with the present version.

R

**Comment by Filco306** [comment]
Thank you very much! Then we can consider this issue closed. 

One last thing I might ask; perhaps this is not the place, but in your paper, you mention that TransE "[...] only supports NegSamp+MR and NegSamp+CE); does it not support a KvsAll? 

Best
F

**Comment by rgemulla** [comment]
For TransE, torch.cdistused to fail/run out of memory, not sure if it still does with recent PyTorch versions. For negative sampling, we default to the "triple" implementation  (see transe.py), which works around this issue.

**Comment by Filco306** [comment]
Ah, okay! So KvsAll should theoretically work with KvsAll, but it just ran out of memory, right? Thank you, I became confused; I had difficulties seeing why it would not work, and.I just ran a KvsAll experiment using TransE on FB15K-237 and it worked for me, so I thought my results for that might not be valid, but then I guess they are :) 

Thanks!

**Comment by rgemulla** [comment]
Right! If it now also works on the larger datasets, we may consider updating the default configuration to make it faster for everybody.
