### ISSUE TITLE
Preprocessing dataset for a new model

### ISSUE THREAD

**Issue by Filco306** [uma-pi1/kge#227]
Hello, 

Thank you for a great repository! I have a new idea for a model which I want to evaluate, but for it to work, I need to preprocess the training triplets to create an initial matrix. Is there any example of how to do this in the framework? 

Thank you!

**Comment by rgemulla** [comment]
Have a look in the [data](https://github.com/uma-pi1/kge/tree/master/data) folder. All the preprocessing code is there + an example of custom preprocessing for the wn11 dataset.

**Comment by samuelbroscheit** [comment]
You can also consider to use the KvsAll index data structure ---which is essentially a sparse matrix of a set of triples--- as a starting point.

https://github.com/uma-pi1/kge/blob/308cebd21e58119d05b1c8613c195cdafe0a112b/kge/indexing.py#L194

**Comment by Filco306** [comment]
Hello again, 

Thank you for your quick replies! I think I was too vague; what I essentially want to do is to give the initialization of the embeddings a starting point that depends on the data, rather than initializing them uniformly at random or through normal distributions. Is this possible?

**Comment by AdrianKs** [comment]
I think you need to extend the initialize function with the specific functionality you want to have:
https://github.com/uma-pi1/kge/blob/308cebd21e58119d05b1c8613c195cdafe0a112b/kge/model/kge_model.py#L52

Here, you could add a new option which initializes the embeddings in a fashion you'd like. You can access the triples with `self.dataset.split("train")`.

**Comment by Filco306** [comment]
This is great!!! Thank you so much!! I will try this and get back if I run into any problems :D
