### ISSUE TITLE
Error when training transe using the sota config

### ISSUE THREAD

**Issue by jwzhi** [uma-pi1/kge#230]
Hi,

I am trying to try transe using the best hyperparameters given in config.yaml on FB15k-237. Here is the error I got on epoch 5 `ValueError: Error in tie-handling. The scores assigned to a triple by the SPO and SP_/_PO scoring implementations were not 'equal' given the configured tolerances. Verify the model's scoring implementations or consider increasing tie-handling tolerances.` I don't really have much idea about why this happens. Can you help me with this?

Thanks,

**Comment by rgemulla** [comment]
Thank you for reporting this!

@AdrianKs This is due to PR #224, I suppose. Do you want to have a look?

**Comment by rgemulla** [comment]
@jwzhi As a temporary workaround, you may work with commit 2ecac7fa8fd743f231519ad059665488440bc616 for now.

**Comment by rgemulla** [comment]
I agree, let's use "donot_use_mm_for_euclid_dist" throughout whenever using cdist (as we do care about close-by values). The relevant issue for Pytorch is: https://github.com/pytorch/pytorch/issues/42479

**Comment by AdrianKs** [comment]
fixed in 5127cf287488a3abfc2e8b698fad22085829a9aa
