### ISSUE TITLE
Hyperparameter tuning not working?

### ISSUE THREAD

**Issue by owenyoung75** [uma-pi1/kge#235]
I'm trying to use hyperparam searching provided, but find the `results` values in each `checkpoint_00001.pt` file is always a list of nones, making the best model identification impossible with all mrr values missing.

Is there something I'm doing wrong here?

**Comment by rgemulla** [comment]
Please update libkge; I've pushed a fix for this problem this morning.

**Comment by owenyoung75** [comment]
Solved. Thanks @rgemulla !!
