### ISSUE TITLE
ERROR: gpytorch 1.5.1 has requirement torch>=1.8.1, but you'll have torch 1.7.1+cu110 which is incompatible.

### ISSUE THREAD

**Issue by lihuiliullh** [uma-pi1/kge#246]
Hi, I met a problem when I tried to install kge.

ERROR: gpytorch 1.5.1 has requirement torch>=1.8.1, but you'll have torch 1.7.1+cu110 which is incompatible.
ERROR: botorch 0.5.1 has requirement torch>=1.8.1, but you'll have torch 1.7.1+cu110 which is incompatible.

Can you help me?

**Comment by rufex2001** [comment]
It seems your installation of libkge is conflicting with other unrelated
libraries you have installed. Have you tried installing libkge in a
separate python environment?

lihuiliullh ***@***.***> schrieb am Fr. 19. Nov. 2021 um
20:42:

**Comment by lihuiliullh** [comment]
Yes, I installed it in a separate python environment. Can you tell me which version of gpytorch  and botorch you use?

**Comment by rgemulla** [comment]
Fixed in ed53b69aff350de33b236736c86e1ac4e33e3421. Please reinstall via "pip -e ." and reopen if the problem still arises.
