### ISSUE TITLE
can you write some detailed tutorial on writing configuration file?

### ISSUE THREAD

**Issue by lihuiliullh** [uma-pi1/kge#247]
can you write some detailed tutorial on writing configuration file? Currently, I find out that the way to learn how to write configuration file is very limited. I read those examples you give, but still barely understand it.

job.type: train
dataset.name: fb15k-237

train:
  optimizer: Adagrad
  optimizer_args:
    lr: 0.2

valid:
  every: 5
  metric: mean_reciprocal_rank_filtered

model: complex
lookup_embedder:
  dim: 100
  regularize_weight: 0.8e-7

**Comment by rufex2001** [comment]
My suggestions would be to:

1. Get familiat with the YAML format
2. Go through the config-default.yaml file to get familiar with the
available configuration options
3. Get familiar with the examples in the examples folder to see how to
combine general config keys with model or embedder specific keys.
4. See something like the following file for an example of a search config
file:

https://github.com/uma-pi1/kge-iclr20/blob/master/config_files/iclr2020/fb15k-237/complex-1vsAll-kl/config.yaml

5. Modify all of the above to produce the config file you need.

**Comment by rgemulla** [comment]
@lihuiliullh As @rufex2001 said, the config options are well-documented in [config-default.yaml](https://github.com/uma-pi1/kge/blob/master/kge/config-default.yaml)

@rufex2001 Perhaps we should point out more clearly that this file is the one to look for documentation.

**Comment by rgemulla** [comment]
Added a FAQ entry.
