### ISSUE TITLE
Fail to preprocess Yago3-10 and DBPedia500

### ISSUE THREAD

**Issue by JothamWong** [uma-pi1/kge#251]
Hello,

Running the download_all.sh script successfully downloads the abovementioned datasets but runs into issue when processing them, with error "UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 1086: character maps to <undefined>".

I tried to fix the issue by adding an encoding="utf-8" argument to the read file but it did not fix the problem. 

Thank you for assisting.

**Comment by AdrianKs** [comment]
Hello,
i just cloned the newest version of the repository and ran `bash download_all.sh` in the data directory. Everything worked as expected. Data is downloaded and preprocessed.
I am working on Ubuntu 20. 

Which operating system are you working on?

**Comment by psychicmario** [comment]
Windows 10

**Comment by rgemulla** [comment]
@ psychicmario This is most likely due to a mismatch of encodings in your setup. Please provide the full stack trace to see where the error actually arises.

Note that we generally do not support the Windows platform. Under Windows, consider using WSL instead.
