### ISSUE TITLE
web.informatik.uni-mannheim.de not accesible

### ISSUE THREAD

**Issue by tostenzel** [uma-pi1/kge#258]
I can't download the datasets (see download_all.sh), e.g. from https://web.informatik.uni-mannheim.de/pi1/kge-datasets/toy.tar.gz

Feel free to close this issue if this was only temporarily and the webpage is accessible again.

**Comment by rufex2001** [comment]
The server seems to be down at the moment. I'm looking into it, so
hopefully it's back soon.

**Comment by rufex2001** [comment]
It's up again! Feel free to open the issue again if not available yet for some reason.
