### ISSUE TITLE
Relation Prediction

### ISSUE THREAD

**Issue by SRL94** [uma-pi1/kge#266]
Hi,

After training the model, can I use the trained model to predict relation? That is, given a subject-object pair (s, o), the trained model predicts the relation r. Is it "score_so()"?

Best regards
Sirui

**Comment by SRL94** [comment]
I got this issue when using "score_so()":
"The reciprocal relations model cannot score relations".

**Comment by rufex2001** [comment]
You can't use the reciprocal relations model for predicting relations, as
these models have two embeddings for each relation, each with different
semantics, So, it's unclear which of the two to use when predicting
relations. There are works on this, but as far as I understand there is no
principled way to do this and we currently don't support this. I suggest
you turn off the use of reciprocal relations when training your model.

**Comment by SRL94** [comment]
Thank you for the reply. I tired to turn off the use of reciprocal relations when training ConvE but it does not work.

**Comment by rgemulla** [comment]
Yes, ConvE requires reciprocal relations.
