### ISSUE TITLE
ERROR: file:///content does not appear to be a Python project: neither 'setup.py' nor 'pyproject.toml' found.

### ISSUE THREAD

**Issue by halima752** [uma-pi1/kge#276]
Hi,
I'm trying to install the package in colab :
             !git clone https://github.com/uma-pi1/kge.git
             !cd kge
             !pip install -e .
and this error appears :
ERROR: file:///content does not appear to be a Python project: neither 'setup.py' nor 'pyproject.toml' found.
could you help me to solve this issue?

**Comment by rgemulla** [comment]
I've just tested the above code in Colab, Python 3 runtime, without problems.
