### ISSUE TITLE
generate embeddings

### ISSUE THREAD

**Issue by halimaaol** [uma-pi1/kge#277]
Hi 
I have generated a chekpoint.pt for a dataset. and I want to generate embeddings for a specific list of entities. can you help me to generate embeddings ?

**Comment by rgemulla** [comment]
Have a look at [here](https://github.com/uma-pi1/kge#use-a-pretrained-model-in-an-application) on how to work with a checkpoint. Given ```model``` in that code, use the models embedders; e.g. ```model.get_s_embedder().embed(indexes)```, where ```indexes``` is an array holding the indexes of the entities for which you'd like to extract embeddings.
