### ISSUE TITLE
Computation of penalty terms

### ISSUE THREAD

**Issue by rgemulla** [uma-pi1/kge#41]
Commit e667cf9cc70819085569eaab8edff813a17e5796 changes the way penalties are interpreted for many models. The penalty term is currently computed only once per embedding, but with this change it's computed twice if subject and object embedder are the same (a common case). Instead of calling penalty twice, the code should check whether they are the same and, if so, call penalty only once.

**Comment by samuelbroscheit** [comment]
Is this currently being worked on already?

**Comment by rgemulla** [comment]
Yes, by @Nzteb

**Comment by rgemulla** [comment]
Closed with #101
