### ISSUE TITLE
'dump trace' for a search folder should contain search's child process folder and search's child process job_id

### ISSUE THREAD

**Issue by samuelbroscheit** [uma-pi1/kge#74]
right now kge dump trace for a search folder gives no clue which search folder contains a specific job's files.

**Comment by rgemulla** [comment]
Use ``--keys folder child_job_id``. I you want default keys, use a keys file.

**Comment by samuelbroscheit** [comment]
Ah cool. Didn't know this already works, thanks!

**Comment by samuelbroscheit** [comment]
Would be nice to add it per default when dumping a search folder?

**Comment by rgemulla** [comment]
Currently, the dumping model does not know the job type, it only looks at traces. 

I agree that it would make sense to add subfolders as a default key. The best way to handle this may be by providing a default keys file that LibKGE uses unless another one is specified.

@Nzteb Do you want to take this?

**Comment by rgemulla** [comment]
For now, I added a "subfolder" key to all "dump trace" outputs. If it's not a search job, the subfolder will simply be empty.

**Comment by rgemulla** [comment]
We actually do distinguish job types during training. Now "child_folder" and "child_job_id" is added to search trace output (only).
