### ISSUE TITLE
Use entry_points to make vanity CLI script

### ISSUE THREAD

**Issue by cthoyt** [uma-pi1/kge#76]
Rather than providing kge.py, you can use the `console_scripts` entry point to define a CLI that automatically gets installed and made available in the shell with `pip install .`

Would be happy to send a PR!

**Comment by rgemulla** [comment]
Sounds great. I understand that this registers a command called ``kge`` that runs our existing ``kge.py``, correct? That's actually how we do it internally (using a shell alias ``alias kge=$KGE_HOME/kge.py``). The approach with ``console_scripts`` is much nicer though. A PR is very much welcome!
