### ISSUE TITLE
Improve seeding with ax

### ISSUE THREAD

**Issue by rgemulla** [uma-pi1/kge#84]
Make SOBOAL seed configurable as `ax_search.sobol_seed`, default to 0.

Also, seed 0 is currently used twice in the code. It looks like that's for different purposes, which is problematic (not sure).

**Comment by samuelbroscheit** [comment]
Adressed in https://github.com/uma-pi1/kge/commit/12dbd0bceda2fe4717cafec64ebfa1889880b7fe
