### ISSUE TITLE
Minimized configs for reciprocal_relations_model are missing base_model import

### ISSUE THREAD

**Issue by samuelbroscheit** [uma-pi1/kge#89]
The minimized configs for our best_models that use reciprocal_relations_model are missing the base_model import.

This leads to

> KeyError: "Key 'distmult.entity_embedder.dropout' cannot be set because key 'distmult' does not exist and no new keys are allowed to be created at root level."

for our best model 

http://web.informatik.uni-mannheim.de/pi1/iclr2020-models/fb15k-237-distmult.yaml

Possible fixes:

1. minimal configs should retain the import statement per default
2. reciprocal_relations_mode.base_model triggers base model import

**Comment by AdrianKs** [comment]
we should also remove specific GPU indentifiers from the config files.

As for example change:
job.device: cuda:3 to job.device: cuda

otherwise people with only one gpu can't run it

**Comment by samuelbroscheit** [comment]
Yes saw that too, good suggestion.

**Comment by rgemulla** [comment]
Missing import statement in exported config fixed in 47e575f.

@rufex2001: I am leaving this open until the relevant minimal configs are regenerated.

**Comment by rgemulla** [comment]
> we should also remove specific GPU indentifiers from the config files.

Yes, although I suggest to remove the device completely for any configs on the website (instead of renaming it).

**Comment by samuelbroscheit** [comment]
> > we should also remove specific GPU indentifiers from the config files.
> 
> Yes, although I suggest to remove the device completely for any configs on the website (instead of renaming it).

Our default device is always cuda, which is also reflected in the quick start, why would we deviate for the best configs?

**Comment by rufex2001** [comment]
Minimal configs updated in kge-iclr20 repo.

**Comment by rgemulla** [comment]
But not yet in this one.

**Comment by rufex2001** [comment]
Servers have been updated.

**Comment by samuelbroscheit** [comment]
The job.device is still in the configs.

**Comment by rufex2001** [comment]
How do we implement this? Remove from all types of config dumps? Just
minimal? I suggest to keep it in raw and full because their names suggest
that, but drop it from minimal. Rainer's suggestion says "from the
website", but I'd like to keep this automated, rather than having to remove
them manually if the dumps will still include them.

**Comment by samuelbroscheit** [comment]
`kge dump trace` could take option --keep (f.ex. import) and --drop (f.ex. job.device) which we can use to create the website configs. This keeps it automatic.

**Comment by rgemulla** [comment]
You  mean ``kge dump config``. The parameters you suggest are already there and called ``--exclude`` and ``--include``.

**Comment by rufex2001** [comment]
That feature is already there, so I can already use it for automation. I
thought we wanted to make it more permanent by removing this by default.

**Comment by samuelbroscheit** [comment]
Yes just realized this.

**Comment by rufex2001** [comment]
How about now?

**Comment by rgemulla** [comment]
Looks good. Please close once done.
