### ISSUE TITLE
Error when trying ax search

### ISSUE THREAD

**Issue by apoorvumang** [uma-pi1/kge#90]
Hi

Training is working fine (train config in README). However when I try to do hyperparameter search using the config provided in README, I get following error:

```
Traceback (most recent call last):
  File "/scratche/home/apoorv/kge/env/bin/kge", line 11, in <module>
    load_entry_point('libkge', 'console_scripts', 'kge')()
  File "/scratche/home/apoorv/kge/kge/cli.py", line 282, in main
    raise e from None
  File "/scratche/home/apoorv/kge/kge/cli.py", line 278, in main
    job.run()
  File "/scratche/home/apoorv/kge/kge/job/auto_search.py", line 111, in run
    self.init_search()
  File "/scratche/home/apoorv/kge/kge/job/ax_search.py", line 43, in init_search
    model_kwargs={'seed': 0}
TypeError: __new__() got an unexpected keyword argument 'num_arms'
```

I created a folder 'wn' and added the config.yaml file. Then I ran` kge resume wn`
I have attached kge.log that was created.
Any help would be appreciated!
Thanks
Apoorv
[kge.log](https://github.com/uma-pi1/kge/files/4456960/kge.log)

**Comment by rgemulla** [comment]
I updated the example in the README slightly so that it uses Complex (there was an unrelated issue with this particular example).

I just tried and the updated example works fine. If you still see this problem, what are your Pytorch and Ax versions?

**Comment by apoorvumang** [comment]
I'm still seeing the same problem :(

```
>>> torch.__version__
'1.4.0'
>>> ax.__version__
'0.1.10'
```

**Comment by apoorvumang** [comment]
I commented the line  `num_sobol_trials: 10` and the code works. Is at an issue with ax on my side?

**Comment by AdrianKs** [comment]
Ax changed their parameter names with the latest version.
Ycou can compare the names here:
https://ax.dev/versions/0.1.8/api/_modules/ax/modelbridge/dispatch_utils.html
https://ax.dev/versions/latest/api/_modules/ax/modelbridge/dispatch_utils.html

I created a PR to fix that.

**Comment by apoorvumang** [comment]
Thanks!
